name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13 # Intel
            target: x86_64-apple-darwin
          - os: macos-14 # ARM
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          cd target/${{ matrix.target }}/release
          strip web3insights-dw || true
          tar -czvf ../../../web3insights-dw-${{ matrix.target }}.tar.gz web3insights-dw
          cd ../../../

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web3insights-dw-${{ matrix.target }}
          path: web3insights-dw-${{ matrix.target }}.tar.gz
          retention-days: 30
